import { writeFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * Layer 2 of determinism: a runtime-level sandbox that pins the controllable
 * nondeterminism sources. Pinning happens by replacing language-runtime globals
 * (the clock, the randomness primitive, the high-resolution timer) and denying
 * live network, loaded as a vitest setup file so it runs before every test.
 *
 * This is deliberately not kernel-level record-and-replay: that would buy a
 * small residue of edge cases at a large complexity cost and is out of scope.
 */

/** Name of the setup file written into a worktree. */
export const SANDBOX_SETUP_FILE = "claimcheck.sandbox.js";
/** Name of the general vitest config written into a worktree. */
export const SANDBOX_CONFIG_FILE = "claimcheck.vitest.config.ts";

/**
 * The setup file body. Pure JavaScript so it runs without transform concerns.
 * The fixed epoch and the seeded PRNG are constants so every run pins to the
 * same values, which is what makes a clock- or random-dependent test stable.
 */
const SANDBOX_BODY = `// Generated by ClaimCheck. Pins controllable nondeterminism sources.
// Each pin is independent: a target that cannot be reassigned must not abort
// the others, so every pin is guarded.
const FIXED_NOW = 1700000000000;

function pin(target, key, value) {
  try {
    Object.defineProperty(target, key, {
      value,
      writable: true,
      configurable: true,
    });
  } catch (_e) {
    try {
      target[key] = value;
    } catch (_e2) {
      // Genuinely non-configurable: leave it. The static scan still flags it.
    }
  }
}

const RealDate = globalThis.Date;
class FrozenDate extends RealDate {
  constructor(...args) {
    if (args.length === 0) {
      super(FIXED_NOW);
    } else {
      super(...args);
    }
  }
  static now() {
    return FIXED_NOW;
  }
}
pin(globalThis, "Date", FrozenDate);

let __seed = 0x2545f491;
pin(globalThis.Math, "random", function random() {
  __seed |= 0;
  __seed = (__seed + 0x6d2b79f5) | 0;
  let t = Math.imul(__seed ^ (__seed >>> 15), 1 | __seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
});

let __perf = 0;
if (globalThis.performance && typeof globalThis.performance.now === "function") {
  pin(globalThis.performance, "now", function now() {
    __perf += 1;
    return __perf;
  });
}

// Seeded counter shared by the crypto pins, independent of Math.random's state
// so instrumentation order does not couple the two streams.
let __cryptoSeed = 0x9e3779b9;
function __cryptoByte() {
  __cryptoSeed = (__cryptoSeed + 0x6d2b79f5) | 0;
  let t = Math.imul(__cryptoSeed ^ (__cryptoSeed >>> 15), 1 | __cryptoSeed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return (t ^ (t >>> 14)) & 0xff;
}
// crypto.getRandomValues is a non-configurable own property and crypto.subtle
// carries a brand check, so the two random methods cannot be shadowed in place.
// globalThis.crypto itself is configurable, so pin a Proxy that overrides the
// two random sources and delegates everything else to the real Crypto with the
// correct receiver, leaving subtle and the rest intact.
const __realCrypto = globalThis.crypto;
if (__realCrypto && typeof __realCrypto.getRandomValues === "function") {
  let __uuid = 0;
  function detRandomUUID() {
    __uuid += 1;
    const tail = __uuid.toString(16).padStart(12, "0").slice(-12);
    // A fixed, valid v4-shaped UUID whose only varying field is a counter, so
    // successive calls are distinct yet identical across runs.
    return "00000000-0000-4000-8000-" + tail;
  }
  function detGetRandomValues(buffer) {
    if (buffer && typeof buffer.length === "number") {
      for (let i = 0; i < buffer.length; i++) buffer[i] = __cryptoByte();
    }
    return buffer;
  }
  const pinnedCrypto = new Proxy(__realCrypto, {
    get(target, prop, receiver) {
      if (prop === "getRandomValues") return detGetRandomValues;
      if (prop === "randomUUID") return detRandomUUID;
      const value = Reflect.get(target, prop, receiver);
      return typeof value === "function" ? value.bind(target) : value;
    },
  });
  pin(globalThis, "crypto", pinnedCrypto);
}

pin(globalThis, "fetch", function fetch() {
  throw new Error(
    "claimcheck-sandbox: live network access is denied; record a fixture or the test is quarantined",
  );
});
`;

/** Build the vitest config that loads the sandbox setup before every test. */
function configBody(include?: readonly string[]): string {
  const includeLine =
    include && include.length > 0
      ? `    include: ${JSON.stringify([...include])},\n`
      : "";
  return `import { defineConfig } from "vitest/config";
export default defineConfig({
  test: {
    setupFiles: ["./${SANDBOX_SETUP_FILE}"],
${includeLine}    pool: "forks",
  },
});
`;
}

/**
 * Write only the sandbox setup file into a worktree. Idempotent; safe to call
 * from any run that needs the pins in place before its config references them.
 *
 * @param worktreeDir - the worktree to write into.
 */
export async function writeSandboxSetup(worktreeDir: string): Promise<void> {
  await writeFile(join(worktreeDir, SANDBOX_SETUP_FILE), SANDBOX_BODY, "utf8");
}

/**
 * Write the sandbox setup file and a vitest config into a worktree.
 *
 * @param worktreeDir - the worktree to prepare; node_modules must be linked.
 * @returns the repo-relative config and setup file names.
 */
export async function prepareSandbox(
  worktreeDir: string,
): Promise<{ configFile: string; setupFile: string }> {
  await writeSandboxSetup(worktreeDir);
  await writeFile(
    join(worktreeDir, SANDBOX_CONFIG_FILE),
    configBody(),
    "utf8",
  );
  return { configFile: SANDBOX_CONFIG_FILE, setupFile: SANDBOX_SETUP_FILE };
}

/**
 * Build a scoped vitest config body that loads the sandbox and restricts the
 * test set, used by the mutation runner so a deliberately regressed sibling
 * test never enters Stryker's initial run.
 *
 * @param include - the test files to include.
 * @returns the config file contents.
 */
export function scopedSandboxConfig(include: readonly string[]): string {
  return configBody(include);
}
